### ISSUE TITLE
[es-ES] [Settings] "Activation Message is on spanish"

### ISSUE THREAD

**Issue by WindowsScriptProgams** [thebookisclosed/l10n#12]
### Store origin

No

### Language

es-ES

### Affected version(s)

Windows Server 2016 Datacenter Version 1607

### Screenshot

![imagen](https://user-images.githubusercontent.com/87366229/164263595-2dd2b91c-2868-423c-86a3-90d32efacc9d.png)

### Details

Viewing the activation the error message it says on spanish

### Proposed solution

Idk

**Comment by thebookisclosed** [comment]
Thank you for your submission. Unfortunately this is an issue concerning Windows resource loading logic, changing the content of a language pack cannot fix it.
